#!/usr/bin/env python3
"""Generate a Markdown reference of an OpenAPI spec's data model.

Reads ``components.schemas`` from an OpenAPI document and writes one Markdown
table per schema. The output is a Docusaurus page: it carries front matter and
is escaped so that the MDX compiler used for ``.md`` files in Docusaurus 3 does
not choke on ``{``, ``<`` or ``&`` coming from the spec.

Usage:
    python3 scripts/generate_schema_doc.py openapi/petstore.yaml docs/openapi/data-model.md
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:  # pragma: no cover - environment guard
    sys.exit("PyYAML is required: pip install -r scripts/requirements.txt")


def md_escape(value) -> str:
    """Escape a spec value for use inside a Markdown table cell.

    ``html.escape`` covers ``& < >``; MDX additionally treats ``{`` and ``}`` as
    expression delimiters, and ``|`` would end the table cell.
    """
    text = html.escape(str(value if value is not None else ""))
    return (
        text.replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("|", "\\|")
        .replace("\r\n", "\n")
        .replace("\n", "<br />")
    )


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def field_type(prop: dict) -> str:
    """Render a property's type, following $ref / composition keywords."""
    if not isinstance(prop, dict):
        return ""
    if "$ref" in prop:
        return ref_name(prop["$ref"])
    for keyword, separator in (("allOf", " + "), ("oneOf", " or "), ("anyOf", " or ")):
        if keyword in prop:
            parts = [field_type(sub) for sub in prop[keyword] if isinstance(sub, dict)]
            parts = [p for p in parts if p]
            return separator.join(parts) if parts else keyword
    if prop.get("type") == "array":
        return f"array of {field_type(prop.get('items', {})) or 'any'}"
    base = prop.get("type", "")
    fmt = prop.get("format")
    if base and fmt:
        return f"{base} ({fmt})"
    return base or ("object" if "properties" in prop else "")


def is_nullable(prop: dict) -> bool:
    # OpenAPI 3.0 uses `nullable: true`; 3.1 uses `type: [..., "null"]`.
    if prop.get("nullable"):
        return True
    declared = prop.get("type")
    return isinstance(declared, list) and "null" in declared


def render(spec: dict, title: str | None, sidebar_position: int | None) -> str:
    info = spec.get("info", {}) or {}
    schemas = (spec.get("components", {}) or {}).get("schemas", {}) or {}

    doc_title = title or info.get("title") or "OpenAPI Data Model"
    description = info.get("description", "")

    out = ["---\n"]
    # JSON strings are valid YAML double-quoted scalars: safe quoting for free.
    out.append(f"title: {json.dumps(doc_title)}\n")
    if sidebar_position is not None:
        out.append(f"sidebar_position: {sidebar_position}\n")
    out.append("---\n\n")
    out.append(
        "{/* Generated by scripts/generate_schema_doc.py — do not edit by hand. */}\n\n"
    )
    out.append(f"# {md_escape(doc_title)}\n\n")

    if description:
        out.append(f"{md_escape(description)}\n\n")

    if not schemas:
        out.append("_No `components.schemas` found in this specification._\n")
        return "".join(out)

    for name, schema in schemas.items():
        schema = schema or {}
        required = set(schema.get("required", []) or [])
        props = schema.get("properties", {}) or {}

        out.append(f"## {md_escape(name)}\n\n")

        if schema.get("description"):
            out.append(f"{md_escape(schema['description'])}\n\n")

        if not props:
            out.append(f"_No properties declared (type: {md_escape(schema.get('type', 'unknown'))})._\n\n")
            continue

        out.append("| Field | Type | Required | Nullable | Enum | Source | Description |\n")
        out.append("|---|---|---|---|---|---|---|\n")

        for field, prop in props.items():
            prop = prop or {}
            enum = ", ".join(str(v) for v in prop.get("enum", []) or [])
            out.append(
                f"| {md_escape(field)} "
                f"| {md_escape(field_type(prop))} "
                f"| {'Yes' if field in required else 'No'} "
                f"| {'Yes' if is_nullable(prop) else 'No'} "
                f"| {md_escape(enum)} "
                f"| {md_escape(prop.get('x-source', ''))} "
                f"| {md_escape(prop.get('description', ''))} |\n"
            )

        out.append("\n")

    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("input", type=Path, help="OpenAPI YAML (or JSON) specification")
    parser.add_argument("output", type=Path, help="Markdown file to write")
    parser.add_argument("--title", help="Override the page title (default: info.title)")
    parser.add_argument(
        "--sidebar-position",
        type=int,
        default=None,
        help="sidebar_position front matter value",
    )
    args = parser.parse_args()

    if not args.input.is_file():
        parser.error(f"specification not found: {args.input}")

    spec = yaml.safe_load(args.input.read_text(encoding="utf-8"))
    if not isinstance(spec, dict):
        parser.error(f"{args.input} does not contain an OpenAPI document")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(spec, args.title, args.sidebar_position), encoding="utf-8")
    print(f"Created {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
